apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: quarkus-repository
spec:
  url: https://github.com/R-Lam/rancher-demo.git
  ref: qa-dev
  frequency: 1m
  type: github # can also be gitlab
  pipelineRef:
    name: quarkus-s2i-pipeline
    namespace: a-cicd # optional: if provided, the pipelinerun will be created in this namespace to reference the pipeline.
    params:
    - name: sha
      expression: commit.sha
    - name: repoUrl
      expression: repoURL
  resources:
    - name: repo
      resourceSpec:
        type: git
        params:
        - name: url
          value: \$(params.repoUrl)
        - name: revision
          value: \$(params.repoSha)
  auth:
    secretRef:
      name:  my-github-secret
    key: token